accounts/urls.py
from django.conf.urls import url, include
from .views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
]

inventario/urls.py
from django.conf.urls import url

from .views import semilla_list, SemillaCreate, semillaUpdate, SemillaDelete

urlpatterns = [
    url(r'^$', semilla_list, name='list'),
    url(r'^inventario/$', SemillaCreate.as_view(), name='inventario'),
    url(r'^inventario/editar/(?P<id_semilla>\d+)$', semillaUpdate, name='inventario_editar'),
    url(r'^inventario/eliminar/(?P<pk>\d+)$', SemillaDelete.as_view(), name='inventario_eliminar'),
]

sistema/urls.py
import os

from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from . import settings

handler404 = 'sistema.views.error404'
handler403 = 'sistema.views.error403'
handler500 = 'sistema.views.error500'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("inventario.urls", namespace="inventario")),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
]

if settings.DEBUG404:
    urlpatterns += (
        url(r'^static/(?P<path>.*)', serve,
            {
                'document_root': os.path.join(os.path.join(os.path.dirname(settings.BASE_DIR), 'static_cdn'))
            }
            ),
    )

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	{% block extrahead%}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/base.css'%}">

	<title>{% block head_title%}Sistema de Inventario{% endblock %}</title>
</head>
<body>
	{% block header%}
	<div class="container">
	<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="nav-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'inventario:list' %}">Inicio</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrar<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'inventario:inventario' %}">Semillas</a></li>
						<li><a href="#">Clientes</a></li>
						<li><a href="#">Proveedores</a></li>
						<li><a href="#">Facturas</a></li>
					</ul>
				</li>
			</ul>
            <form method="GET" class="navbar-form navbar-left">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Buscar" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Buscar</button>
            </form>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Opciones de sesión
                    {% if request.user.is_authenticated %} para <br> {{ request.user }}{% endif %}
                    <span class="caret"></span>
                </a>
				<ul class="dropdown-menu">
					<li>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'accounts:logout' %}">Cerrar sesión</a>
                        {% else %}
                            <a href="{% url 'accounts:login' %}">Iniciar sesión</a>
                        {% endif %}
                    </li>
				</ul>
			</li>
		</ul>
	</div>
	</nav>
	</div>
	{% endblock %}
	{% block content %}
	{% endblock %}
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
  	var js, fjs = d.getElementsByTagName(s)[0];
  	if (d.getElementById(id)) return;
  	js = d.createElement(s); js.id = id;
  	js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v2.9";
  	fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	{% block footer%}
	<div class="container">
	</div>
	{% endblock%}

    <script src="{% static 'js/jquery-2.1.4.min.js'%}"></script>

	<script src="http://code.jquery.com/jquery-2.2.4.min.js"
		integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
		crossorigin="anonymous">
	</script>

	<script src="{% static 'js/bootstrap.js'%}"></script>

	<script src="{% static 'js/marked.min.js'%}"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

	{% block extrajs %}

	{% endblock %}
</body>


</html>

templates/error403.html
{% extends "base.html" %}

{%block head_title%}{{title}}|{{block.super}}{%endblock%}
{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="thumbnail">
                    <div class="caption post-detail-item">
                        <h1>¡Error 403!</h1>
                        <br>
                        <p>
                            Usted está intentando acceder a zona privilegiada.
                        </p>
                        <br>
                        <p>
                            Favor de contactar con el Administrador del sistema.
                        </p>
                        <br>
                        <p>
                            Si lo desea, puede ir a la <a href="{% url 'inventario:list' %}">página principal</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/error404.html
{% extends "base.html" %}

{%block head_title%}{{title}}|{{block.super}}{%endblock%}
{% block content%}
<div class="container">
	<div class="row">
        <div class="col-md-12 text-center">
            <div class="thumbnail">
                <div class="caption post-detail-item">
                    <h1>¡Error 404!</h1>
                    <br>
                    <p>
                        Lo sentimos, la página o recurso al que intenta acceder no se encuentra disponible.
                    </p>
                    <br>
                    <p>
                        Favor de contactar con el Administrador del sistema.
                    </p>
                    <br>
                    <p>
                        Si lo desea, puede ir a la <a href="{% url 'inventario:list' %}">página principal</a>
                    </p>
                </div>
            </div>
	    </div>
	</div>
</div>

{% endblock %}

templates/error500.html
{% extends "base.html" %}

{%block head_title%}{{title}}|{{block.super}}{%endblock%}
{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="thumbnail">
                    <div class="caption post-detail-item">
                        <h1>¡Error 500!</h1>
                        <br>
                        <p>
                            ¡Lo sentimos! No eres tú, es el servidor.
                        </p>
                        <br>
                        <p>
                            Al parecer tenemos un problema en nuestro servidor.
                        </p>
                        <br>
                        <p>
                            Favor de contactar con el Administrador del sistema.
                        </p>
                        <br>
                        <p>
                            Si lo desea, puede ir a la <a href="{% url 'inventario:list' %}">página principal</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ingreso_semilla.html
{% extends "base.html" %}
{% block extrahead %}{% endblock %}
{% block headtitle %}{{title}}|{{block.super}}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row" >
            <div class='col-md-12 col-sm-12 col-lg-4'>

                <h1>Formulario de Ingreso</h1>
                <br>

                <form method="POST" action="" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <form class="form-inline">
                        <div  class="container">
                            <table id="contenido">
                                <tr>
                                    <td><label for="{{form.Nombre.name}}">{{form.Nombre.label}}</label></td>
                                    <td>{{form.Nombre}}</td>
                                </tr>
                                <tr>
                                    <td><label for="{{form.CantidadExistente.name}}">{{form.CantidadExistente.label}}</label></td>
                                    <td>{{form.CantidadExistente}}</td>
                                </tr>
                                <tr>
                                    <td><label for="{{form.CantidadPorHectarea.name}}">{{form.CantidadPorHectarea.label}}</label></td>
                                    <td>{{form.CantidadPorHectarea}}</td>
                                </tr>
                            </table>
                        </div>
                        <br>
                        <input type="submit" class="btn btn-success" value="Agregar"/>
                    </form>
                </form>
            </div>
            <br>
            <div class="col-md-12 col-sm-12 col-lg-8">

                <table class="table">
                    <thead>
                    <hr>
                    <tr>
                        <td>#</td>
                        <td>Nombre Semilla</td>
                        <td>Cantidad existente</td>
                        <td>Cantidad por hectarea</td>
                        <td>Ediciones disp.</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for list in semilla_list %}
                        <tr>
                            <td>{{list.id}}</td>
                            <td>{{list.Nombre}}</td>
                            <td>{{list.CantidadExistente}}</td>
                            <td>{{list.CantidadPorHectarea}}</td>
                            <td>
                                <a href="{% url 'inventario:inventario_editar' list.id %}">Editar</a>
                                <br>
                                {% if request.user.is_superuser %}
                                    <a href="{% url 'inventario:inventario_eliminar' list.id %}">Eliminar</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/login_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extrahead %}
{{ form.media }}
{% endblock %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
	<h1> {{title}}</h1>
	<hr/>

	<form method="POST" action=''enctype='multipart/form-data'>{% csrf_token %}
		{{form|crispy}}
		<input type="submit" class="btn btn-defaul" value="{{title}}"/>
	</form>

    {% if addition %}
        <br>
        ¿No tienes cuenta?
        <a class="btn btn-default" href="{% url 'accounts:register' %}" role="button">{{addition}}</a>
    {% endif %}
</div>
{% endblock %}

templates/semilla_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center">
    <form method="post">
        {% csrf_token %}
        <h3>¿Desea eliminar el siguiente elemento?</h3>
        <h4>{{object.Nombre}}
            {% if object.CantidadExistente > 0 %}
                con {{ object.CantidadExistente }} semillas.
            {% else %}
                sin semillas.
            {% endif %}
        </h4>
        <button class="btn btn-danger" type="submit"> Eliminar</button>
        <a class="btn btn-default" href="{% url 'inventario:inventario' %}">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/semilla_list.html
{% extends "base.html" %}

{%block head_title%}{{title}}|{{block.super}}{%endblock%}
{% block content%}
<div class="container">
	<div class="row">
	
		<div class="col-md-8">
            {% for obj in object_list %}
                <div class="thumbnail">
                    {% if obj.image %}
                        <img src="{{obj.image.url}}" class="img-responsive"/>
                    {% endif %}
                    <div class="caption post-detail-item">
                        <h3><a href='{{obj.get_absolute_url}}'>{{obj.Nombre}}</a></h3>
                        <p>Cantidad existente: {{obj.CantidadExistente|truncatechars_html:20}}</p>
                        <p>Cantidad que se entregan por hectarea: {{obj.CantidadPorHectarea|truncatechars_html:20}}</p>
                        <p><a href='{{obj.get_absolute_url}}' class="btn btn-primary" role="button">Leer</a></p>
                    </div>
                </div>
            {% endfor %}
			<div class="pagination">
				<span class="step-links">
					{% if object_list.has_previous %}
						<a href="?page={{ object_list.previous_page_number }}
						{% if request.GET.q %}&q={{request.GET.q}}{% endif %} ">Previo</a>
					{% endif %}
					<span class="current">
						Pagina {{ object_list.number }} de {{ object_list.paginator.num_pages }}
					</span>
					{% if object_list.has_next %}
						<a href="?page={{ object_list.next_page_number}}{% if request.GET.q %}&q={{request.GET.q}}{%endif%}">Siguiente</a>
					{% endif %}
				</span>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/update_semilla.html
{% extends "base.html" %}
{% block extrahead %}{% endblock %}
{% block headtitle %}{{title}}|{{block.super}}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row" >
            <div class='text-center'>

                <h1>Formulario de Actualización</h1>
                <br>

                <form method="POST" action="" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <form class="form-inline">
                        <div class="container">
                            <table id="contenido" class="container-fluid">
                                <tr>
                                    <td><label for="{{form.Nombre.name}}">{{form.Nombre.label}}</label></td>
                                    <td>{{form.Nombre}}</td>
                                </tr>
                                <tr>
                                    <td><label for="{{form.CantidadExistente.name}}">{{form.CantidadExistente.label}}</label></td>
                                    <td>{{form.CantidadExistente}}</td>
                                </tr>
                                <tr>
                                    <td><label for="{{form.CantidadPorHectarea.name}}">{{form.CantidadPorHectarea.label}}</label></td>
                                    <td>{{form.CantidadPorHectarea}}</td>
                                </tr>
                            </table>
                        </div>
                        <br>
                        <input type="submit" class="btn btn-warning" value="Actualizar"/>
                        <hr>
                    </form>
                </form>
            </div>
            <br>
        </div>
    </div>
{% endblock %}